# Generated by Django 3.0.8 on 2020-08-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedtestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('download', models.FloatField()),
                ('upload', models.FloatField()),
                ('ping', models.FloatField()),
            ],
        ),
    ]
